<?php

/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'ID' => 'ID Χρήστη',
    'User ID' => 'ID Χρήστη',
    'Image' => 'Φωτογραφία',
    'User Created' => 'Δημιουργία Χρήστης',
    'Date Created' => 'Ημερομηνία Δημιουργίας',
    'User Last Change' => 'Χρήστης τελευταίας αλλαγγής',
    'Date Last Change' => 'Ημερομηνία τελευταίας αλλαγής',
    'Create' => 'Δημιουργία',
    'Created Date' => 'Ημερομηνία Δημιουργίας',
    'Created At' => 'Ημερομηνία Δημιουργίας',
    'Created By' => 'Δημιουργία χρήστης',
    'Updated At' => 'Ημερομηνία Αλλαγής',
    'Updated By' => 'Αλλαγή Χρήστης',
    'Title' => 'Τίτλος',
    'Update {modelClass}: ' => 'Αλλαγή {modelClass}: ',
    'Add' => 'Προσθήκη',
    'User Name' => 'Όνομα Χρήστη',
    'Full Name' => 'Πλήρες Όνομα',
    'Status' => 'Κατάσταση',
    'Time Zone' => 'Ζώνη Ώρας',
    'Username' => 'Όνομα Χρήστη',
    'Last Login' => 'Τελευταία είσοδος',
    'Create New User' => 'Δημιουργία Νέου Χρήστη',
    'View All Users' => 'Εμφάνιση όλων των Χρηστών',
    'Please fill out the following fields to create User:' => 'Παρακαλώ συμπληρώστε τα παρακάτω πεδία για την δημιουργία Χρήστη :',
    'File Manager' => 'Διαχείριση Αρχείων',
    'Settings' => 'Ρυθμίσεις',
    'Manage Users' => 'Διαχείρηση Χρηστών',
    'Οpen File Manager' => 'Διαχείριση Αρχείων',
    'Update' => 'Αλλαγή',
    'Delete' => 'Διαγραφή',
    'Reset Password' => 'Επαναφορά Password',
    'Set Password' => 'Ορισμός Password',
    'Account' => 'Λογαριασμός',
    'Profile' => 'Προφίλ',
    'Roles' => 'Ρόλοι',
    'Update Roles' => 'Αλλαγή Ρόλων',
    'Role Name' => 'Όνομα Ρόλου',
    'Description' => 'Περιγραφή',
    'Created' => 'Δημιουργήθηκε',
    'Updated' => 'Αλλάχτηκε',
    'Users' => 'Χρήστες',
    'View User' => 'Εμφάνιση Χρήστη',
    'Profile not update yet !' => 'Το Προφίλ δεν έχει ενημερωθεί ακόμη !',
    'Update User Profile' => 'Ενημέρωση Προφίλ Χρήστη',
    'Index Users' => 'Λίστα Χρηστών',
    'First Name' => 'Όνομα',
    'Last Name' => 'Επώνυμο',
    'Gender' => 'Φύλο',
    'File for Profile Image' => 'Αρχείο Φωτογραφίας Προφίλ',
    'Profile Image' => 'Φωτογραφία Προφίλ',
    'Birth Date' => 'Ημερομηνία Γέννησης',
    'Male' => 'Άνδρας',
    'Female' => 'Γυναίκα',
    'Active' => 'Ενεργός',
    'Inactive' => 'Ανενεργός',
    'Change Password' => 'Αλλαγή Password',
    'Latest Members' => 'Πρόσφατοι χρήστες',
    'My Account Profile' => 'O Λογαριασμός μου',
   
];
